# Use the latest LTS version of Node.js
FROM node:18-alpine

WORKDIR /app

# Install dependencies first (better caching)
COPY package*.json ./
RUN npm install

# Copy all project files
COPY . .

EXPOSE 5173

# Run migrations, regenerate client, and then start dev server
CMD npx prisma migrate dev && npx prisma generate && npm run dev
